(TeX-add-style-hook "ProjectProposal.KinectControls.KhaledSalahElDinTahaMahmoud"
 (lambda ()
    (TeX-run-style-hooks
     "url"
     "hyperref"
     "model"
     "driven"
     "design"
     "Kinect"
     "assisted"
     "living"
     "home"
     "devices}"
     "the"
     "German"
     "University"
     "in"
     "Cairo"
     "GUC"
     "(http://met.guc.edu.eg/)}"
     "relsize"
     "xcolor"
     "microtype"
     "mathdesign"
     "adobe-utopia"
     "fontenc"
     "T1"
     "latex2e"
     "art10"
     "article"
     "a4paper")))

